# Generated by Django 5.1.1 on 2024-09-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hasnat_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='screenshot',
        ),
    ]
