# Generated by Django 5.1.1 on 2024-10-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hasnat_app', '0006_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
