# Generated by Django 5.1.1 on 2024-10-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hasnat_app', '0008_user_phone_number_alter_user_email'),
    ]

    operations = [
    ]
