# Generated by Django 4.2.16 on 2024-10-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hasnat_app', '0010_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='screenshot',
            name='bug',
        ),
        migrations.DeleteModel(
            name='Bug',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Screenshot',
        ),
    ]
